version: '3.8'

services:
  app:
    image: formalize:development
    build: .
    tty: true
    stdin_open: true
    environment:
      NODE_ENV: development
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
