version: "3"

services:
  app:
    image: "vue-template:latest"
    build:
      context: .
      dockerfile: "development.Dockerfile"
    environment:
      NODE_ENV: development
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/src/app"
